### PR TITLE
New Fork Maintained At ckabalan/kitty

### PR DESCRIPTION
**Pull request by ckabalan**
It looks like this fork is abandoned. I've started my own fork using the core technical code from this fork. I will continue updating the code at the below link until I stop using Kitty.

https://github.com/ckabalan/kitty

Follow the `brightcolors` branch for the most up-to-date code.

---

**Original PR text below**

This merges in changes from the `v0.20.3` tag at https://github.com/kovidgoyal/kitty .

Thanks for your awesome work on this fork!

I'm happy to submit these PRs in the future when there are major Kitty releases, or if you're looking for help I'm happy to join the GitHub Organization. I previously submitted Pr #3 but saw no response. I'll continue to submit these PRs periodically.

### CODE REVIEW

**Comment by KittyPatch** [comment]
### *_Wow!_*
First, my sincere apologies @ckabalan. This fork had no traction for a few months, but now I see your PRs and a couple of stars to boot. I should have checked in and kept the project up-to-date.

In case you are still interested, I’ve added you as a contributor. I’ll also close this PR in favour of the latest kitty changes from `v0.23.1`.

Please, by all means, continue with your own fork. But I hope that my activity here will renew your (and others) confidence in the future of KittyPatch.

---

There are a few ops-related tasks that need to be addressed:
* Fix the build pipeline
* Add a brew cask for KittyPatch
* Add static hosting/deployment for a KittyPatch site

The informal KittyPatch roadmap is as follows:
1. Menu bar customisation — the kitty menu bar is unsightly. I think there are others as well that would like to be able to customise it (or even just switch parts of it off)
2. Great looking defaults — an aesthetically pleasing default config for KittyPatch would help drive adoption by lowering the barrier to entry
3. Smooth scroll — this just may be wishful thinking, but smooth scrolling (as seen in [termite](https://github.com/thestinger/termite)) would make KittyPatch stand out against other GPU-based terminal emulators. Even termite’s spiritual successor [Alacritty](https://github.com/alacritty/alacritty) (⭐️ 34.2k) doesn’t support it! Stalled efforts for kitty exist in [this PR](https://github.com/kovidgoyal/kitty/issues/1123), but there’s still a lot of work to do.

Ultimately, I see KittyPatch as a friendlier kitty. A home for valuable features that don’t make it into kitty, and a performant and minimal terminal that you can just grab and get going with.

Thank you for your contributions so far, and looking forward to working with you!

**Comment by ckabalan** [comment]
I'm happy to start re-contributing here if there are other collaborators. My fork is up to date as of a a few weeks ago, but I omitted all of the KittyPatch "ops-related" changes like rebranding for my own convenience. It was too much to keep syncing all the changes with upstream.

For the roadmap, to be honest I'm only really passionate about the bright bold capabilities. No objection to the other features though.

If I create a new branch with the latest release and as many changes as I can merge will you fix the remaining items? I should be able to give you a fairly concise list. For example, the main Kitty icon for MacOS was changed to follow the Big Sur style guidelines from Apple. I don't believe I have the files you used to add the little bandaid to the KittyPatch icon so I couldn't update that. Once we're in a good place we can merge to master.

Then if there's no point for my fork anymore (since I can now maintain here) I'll just replace with a redirect page.

Thoughts?

**Comment by KittyPatch** [comment]
Will do — and thank you for your effort. Good spot on the icon!

**Comment by ckabalan** [comment]
Hi @KittyPatch , looks like upstream just released v0.24. I've created `feature/v0.24.0-BrightBolds` which is their `v0.24.0` tag plus the minimal code needed to enable the feature. I've confirmed it works and also created the `brightbolds` branch which will just have the latest working version (see the README for that branch).

Anyway, as we talked about, can you create a new feature branch from `feature/v0.24.0-BrightBolds` and re-do all your niceities like the KittyPatch icon based on the updated Kitty icon, and re-do whatever level you want to to distance this from Kovid's project (I noticed you had changed a lot of donation references and build stuff from his project). Once you're happy with it you can merge into `master` and I'll continue to keep that up to date.

If you don't feel like putting in that work that's fine, let me know, and I'll start maintaining the `master` branch with the latest working code and leave behind the KittyPatch branding.

**Comment by KittyPatch** [comment]
👋 Hey @ckabalan! To preserve git history and avoid reapplying the same changes again, I've gone ahead and merged the latest tagged release `v0.24.1` from upstream with `master`: [PR #5](https://github.com/KittyPatch/kitty/pull/5)

Take a look and if you're happy, I'll merge it ASAP

**Comment by KittyPatch** [comment]
I've merged the PR, next step: set up github release publishing in preparation for a homebrew cask.

**Pull request closed without merging**
